# Generated by Django 5.2.7 on 2025-11-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackendModelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        help_text="Config version number (auto-incremented)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name (e.g., 'Production V1', 'High Accuracy Tuning')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What changed in this configuration"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mobilefacenet_weight",
                    models.FloatField(
                        default=0.35,
                        help_text="Weight for MobileFaceNet (0.0 - 1.0). Fast, good for normal conditions.",
                    ),
                ),
                (
                    "arcface_weight",
                    models.FloatField(
                        default=0.35,
                        help_text="Weight for ArcFace W600K (0.0 - 1.0). Banking-grade accuracy.",
                    ),
                ),
                (
                    "adaface_weight",
                    models.FloatField(
                        default=0.3,
                        help_text="Weight for AdaFace (0.0 - 1.0). Quality-adaptive, handles difficult lighting.",
                    ),
                ),
                (
                    "mobilefacenet_threshold",
                    models.FloatField(
                        default=0.5,
                        help_text="Minimum similarity score for MobileFaceNet to consider a match (0.0 - 1.0)",
                    ),
                ),
                (
                    "arcface_threshold",
                    models.FloatField(
                        default=0.25,
                        help_text="Minimum similarity score for ArcFace (0.0 - 1.0). Lower because scores are compressed.",
                    ),
                ),
                (
                    "adaface_threshold",
                    models.FloatField(
                        default=0.4,
                        help_text="Minimum similarity score for AdaFace (0.0 - 1.0)",
                    ),
                ),
                (
                    "high_confidence_threshold",
                    models.FloatField(
                        default=0.55,
                        help_text="Combined score >= this = HIGH confidence match",
                    ),
                ),
                (
                    "medium_confidence_threshold",
                    models.FloatField(
                        default=0.4,
                        help_text="Combined score >= this = MEDIUM confidence match",
                    ),
                ),
                (
                    "match_threshold",
                    models.FloatField(
                        default=0.35,
                        help_text="Minimum combined score to consider a match (below this = NO MATCH)",
                    ),
                ),
                (
                    "minimum_consensus",
                    models.IntegerField(
                        default=2,
                        help_text="Minimum number of models that must agree (1-3)",
                    ),
                ),
                (
                    "require_all_agree",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all 3 models must agree for VERIFIED status",
                    ),
                ),
                (
                    "use_weighted_vote",
                    models.BooleanField(
                        default=True,
                        help_text="If True, use model weights when voting. If False, each model gets equal vote.",
                    ),
                ),
                (
                    "mobilefacenet_temperature_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable temperature scaling for MobileFaceNet",
                    ),
                ),
                (
                    "mobilefacenet_temperature",
                    models.FloatField(
                        default=1.0,
                        help_text="Temperature value (higher = spread out scores)",
                    ),
                ),
                (
                    "mobilefacenet_shift",
                    models.FloatField(default=0.0, help_text="Shift scores before scaling"),
                ),
                (
                    "arcface_temperature_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable temperature scaling for ArcFace (recommended)",
                    ),
                ),
                (
                    "arcface_temperature",
                    models.FloatField(
                        default=3.0,
                        help_text="Temperature value (ArcFace scores are compressed, need spreading)",
                    ),
                ),
                (
                    "arcface_shift",
                    models.FloatField(
                        default=-0.15,
                        help_text="Shift scores before scaling (center around typical score)",
                    ),
                ),
                (
                    "adaface_temperature_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable temperature scaling for AdaFace",
                    ),
                ),
                (
                    "adaface_temperature",
                    models.FloatField(default=1.0, help_text="Temperature value"),
                ),
                (
                    "adaface_shift",
                    models.FloatField(default=0.0, help_text="Shift scores before scaling"),
                ),
            ],
            options={
                "verbose_name": "Backend Model Configuration",
                "verbose_name_plural": "Backend Model Configurations",
                "ordering": ["-version"],
            },
        ),
    ]
