# Generated by Django 5.2.7 on 2025-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceRecognitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., 'mobilefacenet', 'w600k_r50')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Display name (e.g., 'MobileFaceNet', 'W600K ResNet50')",
                        max_length=255,
                    ),
                ),
                (
                    "gcs_bucket",
                    models.CharField(
                        default="easypool-ml-models",
                        help_text="GCS bucket name",
                        max_length=255,
                    ),
                ),
                (
                    "gcs_path",
                    models.CharField(
                        help_text="Path in GCS (e.g., 'face-recognition/v1/w600k_r50.onnx')",
                        max_length=500,
                    ),
                ),
                (
                    "local_filename",
                    models.CharField(
                        help_text="Local filename (e.g., 'w600k_r50.onnx')",
                        max_length=255,
                    ),
                ),
                (
                    "file_size_mb",
                    models.IntegerField(
                        default=0,
                        help_text="Approximate file size in MB (for progress indication)",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, help_text="Enable this model for verification"),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.33,
                        help_text="Weight in ensemble (0.0 - 1.0). All enabled models' weights should sum to 1.0",
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        default=0.4,
                        help_text="Minimum similarity score to consider a match (0.0 - 1.0)",
                    ),
                ),
                (
                    "temperature_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable temperature scaling for this model",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=1.0,
                        help_text="Temperature value (higher = spread out scores)",
                    ),
                ),
                (
                    "shift",
                    models.FloatField(default=0.0, help_text="Shift scores before scaling"),
                ),
                (
                    "inference_class",
                    models.CharField(
                        help_text="Full path to inference class (e.g., 'ml_models.face_recognition.inference.w600k_r50.W600KModel')",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Face Recognition Model",
                "verbose_name_plural": "Face Recognition Models",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="backendmodelconfiguration",
            name="high_confidence_threshold",
            field=models.FloatField(
                default=0.6,
                help_text="Combined score >= this = HIGH confidence match (FAR < 0.1%)",
            ),
        ),
        migrations.AlterField(
            model_name="backendmodelconfiguration",
            name="medium_confidence_threshold",
            field=models.FloatField(
                default=0.45,
                help_text="Combined score >= this = MEDIUM confidence match",
            ),
        ),
    ]
