# Generated by Django - Data migration to seed default face recognition models

from django.db import migrations


def seed_default_models(apps, schema_editor):
    """Create default face recognition models and 3-model config on first migration"""
    FaceRecognitionModel = apps.get_model("ml_config", "FaceRecognitionModel")
    BackendModelConfiguration = apps.get_model("ml_config", "BackendModelConfiguration")

    defaults = [
        {
            "name": "mobilefacenet",
            "display_name": "MobileFaceNet",
            "gcs_path": "face-recognition/v1/mobilefacenet.tflite",
            "local_filename": "mobilefacenet.tflite",
            "file_size_mb": 5,
            "is_enabled": True,
            "weight": 0.35,
            "threshold": 0.50,
            "temperature_enabled": False,
            "temperature": 1.0,
            "shift": 0.0,
            "inference_class": "ml_models.face_recognition.inference.mobilefacenet.MobileFaceNetModel",
        },
        {
            "name": "arcface_int8",
            "display_name": "ArcFace INT8",
            "gcs_path": "face-recognition/v1/arcface_int8.onnx",
            "local_filename": "arcface_int8.onnx",
            "file_size_mb": 63,
            "is_enabled": True,
            "weight": 0.35,
            "threshold": 0.25,
            "temperature_enabled": True,
            "temperature": 3.0,
            "shift": -0.15,
            "inference_class": "ml_models.face_recognition.inference.arcface_int8.ArcFaceINT8Model",
        },
        {
            "name": "w600k_r50",
            "display_name": "W600K ResNet50",
            "gcs_path": "face-recognition/v1/w600k_r50.onnx",
            "local_filename": "w600k_r50.onnx",
            "file_size_mb": 174,
            "is_enabled": True,
            "weight": 0.30,
            "threshold": 0.40,
            "temperature_enabled": False,
            "temperature": 1.0,
            "shift": 0.0,
            "inference_class": "ml_models.face_recognition.inference.w600k_r50.W600KModel",
        },
    ]

    for model_data in defaults:
        FaceRecognitionModel.objects.get_or_create(name=model_data["name"], defaults=model_data)

    # Create default 3-model BackendModelConfiguration (V2)
    # Deactivate any existing configs first
    BackendModelConfiguration.objects.filter(is_active=True).update(is_active=False)

    BackendModelConfiguration.objects.get_or_create(
        version=2,
        defaults={
            "name": "3-Model Ensemble (MobileFaceNet + ArcFace + W600K)",
            "description": "Banking-grade 3-model consensus with weighted voting. Activate this to use all 3 models.",
            "is_active": True,  # V2 3-model is active by default
            # Weights (sum to 1.0)
            "mobilefacenet_weight": 0.35,
            "arcface_weight": 0.35,
            "adaface_weight": 0.30,  # W600K uses adaface slot
            # Per-model thresholds
            "mobilefacenet_threshold": 0.50,
            "arcface_threshold": 0.25,
            "adaface_threshold": 0.40,
            # Combined thresholds
            "high_confidence_threshold": 0.60,
            "medium_confidence_threshold": 0.45,
            "match_threshold": 0.35,
            # Consensus strategy
            "minimum_consensus": 2,
            "require_all_agree": False,
            "use_weighted_vote": True,
            # Temperature scaling
            "mobilefacenet_temperature_enabled": False,
            "mobilefacenet_temperature": 1.0,
            "mobilefacenet_shift": 0.0,
            "arcface_temperature_enabled": True,
            "arcface_temperature": 3.0,
            "arcface_shift": -0.15,
            "adaface_temperature_enabled": False,
            "adaface_temperature": 1.0,
            "adaface_shift": 0.0,
        },
    )


def reverse_seed(apps, schema_editor):
    """Remove seeded models (optional - keeps them by default)"""
    pass  # Don't delete on reverse migration


class Migration(migrations.Migration):
    dependencies = [
        ("ml_config", "0002_add_face_recognition_model"),
    ]

    operations = [
        migrations.RunPython(seed_default_models, reverse_seed),
    ]
