# Generated by Django - Data migration to seed default face recognition models

from django.db import migrations


def seed_default_models(apps, schema_editor):
    """Create default face recognition models on first migration"""
    FaceRecognitionModel = apps.get_model('ml_config', 'FaceRecognitionModel')

    defaults = [
        {
            "name": "mobilefacenet",
            "display_name": "MobileFaceNet",
            "gcs_path": "face-recognition/v1/mobilefacenet.tflite",
            "local_filename": "mobilefacenet.tflite",
            "file_size_mb": 5,
            "is_enabled": True,
            "weight": 0.35,
            "threshold": 0.50,
            "temperature_enabled": False,
            "temperature": 1.0,
            "shift": 0.0,
            "inference_class": "ml_models.face_recognition.inference.mobilefacenet.MobileFaceNetModel",
        },
        {
            "name": "arcface_int8",
            "display_name": "ArcFace INT8",
            "gcs_path": "face-recognition/v1/arcface_int8.onnx",
            "local_filename": "arcface_int8.onnx",
            "file_size_mb": 63,
            "is_enabled": True,
            "weight": 0.35,
            "threshold": 0.25,
            "temperature_enabled": True,
            "temperature": 3.0,
            "shift": -0.15,
            "inference_class": "ml_models.face_recognition.inference.arcface_int8.ArcFaceINT8Model",
        },
        {
            "name": "w600k_r50",
            "display_name": "W600K ResNet50",
            "gcs_path": "face-recognition/v1/w600k_r50.onnx",
            "local_filename": "w600k_r50.onnx",
            "file_size_mb": 174,
            "is_enabled": True,
            "weight": 0.30,
            "threshold": 0.40,
            "temperature_enabled": False,
            "temperature": 1.0,
            "shift": 0.0,
            "inference_class": "ml_models.face_recognition.inference.w600k_r50.W600KModel",
        },
    ]

    for model_data in defaults:
        FaceRecognitionModel.objects.get_or_create(
            name=model_data["name"],
            defaults=model_data
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded models (optional - keeps them by default)"""
    pass  # Don't delete on reverse migration


class Migration(migrations.Migration):

    dependencies = [
        ('ml_config', '0002_add_face_recognition_model'),
    ]

    operations = [
        migrations.RunPython(seed_default_models, reverse_seed),
    ]
