# Generated by Django 5.2.6 on 2025-10-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
        ("students", "0002_alter_faceembeddingmetadata_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="assigned_bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_students",
                to="buses.bus",
            ),
        ),
        migrations.DeleteModel(
            name="Bus",
        ),
    ]
