# Generated by Django 5.2.7 on 2025-11-02 20:46

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "key_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kiosk_id",
                    models.CharField(help_text="Reference to kiosk device", max_length=100),
                ),
                (
                    "key_hash",
                    models.CharField(help_text="Hashed API key", max_length=255, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name for the key",
                        max_length=100,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object defining scoped permissions",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "api_keys",
                "indexes": [
                    models.Index(fields=["kiosk_id"], name="idx_apikey_kiosk"),
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["is_active"],
                        name="idx_apikey_active",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("API_ACCESS", "API Access"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("student", "Student"),
                            ("bus", "Bus"),
                            ("kiosk", "Kiosk"),
                            ("event", "Boarding Event"),
                            ("notification", "Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                (
                    "changes",
                    models.JSONField(blank=True, help_text="JSON object of changes made", null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="idx_users_email"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="idx_users_username"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "-timestamp"], name="idx_audit_user_time"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["resource_type", "resource_id"], name="idx_audit_resource"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-timestamp"], name="idx_audit_timestamp"),
        ),
    ]
