# Generated by Django 5.2.7 on 2025-11-02 11:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="internal_uuid",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
