# Generated by Django 5.2.7 on 2025-11-14 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("students", "0003_store_photos_in_database"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Approval status for parent users",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_at",
            field=models.DateTimeField(blank=True, help_text="Timestamp when parent was approved", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved this parent user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to Parent record if this user is a parent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_account",
                to="students.parent",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["parent"], name="idx_users_parent"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["approval_status"], name="idx_users_approval_status"),
        ),
    ]
