# Generated by Django 5.2.7 on 2025-11-15 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_parent_approval_system"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="idx_users_parent",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_users_approval_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="approval_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="parent",
        ),
    ]
