# Generated by Django 5.2.7 on 2025-11-02 12:41

import uuid

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import students.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "school_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "parent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.TextField(
                        help_text="Encrypted phone number (plaintext validated as +91XXXXXXXXXX)",
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.TextField(
                        help_text="Encrypted email address (plaintext validated per RFC 5321)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.TextField(help_text="Encrypted name (plaintext validated max 100 chars)"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "parents",
                "indexes": [
                    models.Index(fields=["phone"], name="idx_parents_phone"),
                    models.Index(fields=["email"], name="idx_parents_email"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "school_student_id",
                    models.CharField(
                        help_text="School-provided student ID (e.g., STU-2024-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(help_text="Encrypted at application layer")),
                ("grade", models.CharField(max_length=10)),
                ("section", models.CharField(blank=True, max_length=10)),
                (
                    "address_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Student home address latitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "address_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Student home address longitude",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_bus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_students",
                        to="buses.bus",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="students.school",
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("guardian", "Guardian"),
                            ("grandparent", "Grandparent"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_parents",
                        to="students.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_parents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_parents",
            },
        ),
        migrations.CreateModel(
            name="StudentPhoto",
            fields=[
                (
                    "photo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Student photo file",
                        null=True,
                        upload_to=students.models.student_photo_path,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Primary photo for student"),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When photo was taken",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_photos",
            },
        ),
        migrations.CreateModel(
            name="FaceEmbeddingMetadata",
            fields=[
                (
                    "embedding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="Face recognition model", max_length=100),
                ),
                (
                    "model_version",
                    models.CharField(help_text="Face recognition model version", max_length=50),
                ),
                (
                    "embedding",
                    models.JSONField(
                        default=dict,
                        help_text="The embedding vector as a list of floats",
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(help_text="Face detection quality score (0-1)"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Primary embedding for this photo"),
                ),
                (
                    "captured_at",
                    models.DateTimeField(help_text="When the face was captured"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "student_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_embeddings",
                        to="students.studentphoto",
                    ),
                ),
            ],
            options={
                "db_table": "face_embeddings_metadata",
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["school", "status"], name="idx_students_school_status"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                condition=models.Q(("status", "active")),
                fields=["assigned_bus"],
                name="idx_students_bus_active",
            ),
        ),
        migrations.AddIndex(
            model_name="studentparent",
            index=models.Index(fields=["parent"], name="idx_parent_students"),
        ),
        migrations.AlterUniqueTogether(
            name="studentparent",
            unique_together={("student", "parent")},
        ),
        migrations.AddIndex(
            model_name="studentphoto",
            index=models.Index(fields=["student"], name="idx_photos_student"),
        ),
        migrations.AddIndex(
            model_name="faceembeddingmetadata",
            index=models.Index(
                fields=["student_photo", "model_name", "model_version"],
                name="idx_embeddings_photo_model",
            ),
        ),
    ]
