# Generated by Django 5.2.7 on 2025-11-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(blank=True, help_text="Date student enrolled in school", null=True),
        ),
    ]
