# Generated by Django 5.2.6 on 2025-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faceembeddingmetadata",
            name="model_name",
            field=models.CharField(help_text="Face recognition model", max_length=100),
        ),
    ]
