# Generated by Django 5.2.7 on 2025-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_make_enrollment_date_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentphoto",
            name="photo",
        ),
        migrations.AddField(
            model_name="studentphoto",
            name="photo_content_type",
            field=models.CharField(
                blank=True,
                default="image/jpeg",
                help_text="MIME type (e.g., image/jpeg, image/png)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="studentphoto",
            name="photo_data",
            field=models.BinaryField(blank=True, help_text="Photo binary data stored in database", null=True),
        ),
    ]
