# Generated by Django 5.2.7 on 2025-11-15 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_store_photos_in_database"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Approval status for parent access",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when parent was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved this parent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_parents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked user account for this parent",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(fields=["user"], name="idx_parents_user"),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["approval_status"], name="idx_parents_approval_status"
            ),
        ),
    ]
