# Generated by Django 5.2.7 on 2025-11-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_add_approval_to_parent_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="email",
            field=models.TextField(
                blank=True,
                help_text="Encrypted email address (plaintext validated per RFC 5321)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="phone",
            field=models.TextField(
                blank=True,
                help_text="Encrypted phone number (plaintext validated as +91XXXXXXXXXX)",
                null=True,
            ),
        ),
    ]
