# Generated by Django 5.2.7 on 2025-11-19 14:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_make_parent_phone_email_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentphoto",
            name="submitted_by_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent who submitted this photo (NULL if admin-uploaded)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_photos",
                to="students.parent",
            ),
        ),
        migrations.CreateModel(
            name="FaceEnrollment",
            fields=[
                (
                    "enrollment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photos_data",
                    models.JSONField(
                        help_text="Array of photo data objects from auto-capture session"
                    ),
                ),
                (
                    "photo_count",
                    models.IntegerField(
                        help_text="Number of photos in this enrollment"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_approval",
                        help_text="Approval status",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When parent submitted enrollment",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When enrollment was reviewed", null=True
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Device and capture metadata from parent app",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="Parent who submitted this enrollment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_enrollments",
                        to="students.parent",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this enrollment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student for this enrollment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "face_enrollments",
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="idx_enrollments_student_status",
                    ),
                    models.Index(
                        fields=["parent", "status"],
                        name="idx_enrollments_parent_status",
                    ),
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="idx_enrollments_status_date",
                    ),
                ],
            },
        ),
    ]
