# Generated by Django 5.2.6 on 2025-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_alter_studentphoto_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faceembeddingmetadata",
            name="qdrant_point_id",
        ),
        migrations.AddField(
            model_name="faceembeddingmetadata",
            name="embedding",
            field=models.JSONField(
                default=dict, help_text="The embedding vector as a list of floats"
            ),
        ),
    ]
