# Generated by Django 5.2.7 on 2025-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_remove_faceembeddingmetadata_qdrant_point_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Student home address latitude",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="address_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Student home address longitude",
                max_digits=10,
                null=True,
            ),
        ),
    ]
