# Generated by Django 5.2.7 on 2025-10-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_student_address_latitude_student_address_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="school_student_id",
            field=models.CharField(
                blank=True,
                help_text="School-provided student ID (e.g., STU-2024-001)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
