# Generated by Django 5.2.7 on 2025-10-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_add_school_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school_student_id",
            field=models.CharField(
                default="STU-TEMP",
                help_text="School-provided student ID (e.g., STU-2024-001)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
