# Generated by Django 5.2.7 on 2025-11-19 08:32

from django.db import migrations, models
import django.db.models.deletion

import notifications.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0004_add_approval_to_parent_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "boarding",
                    models.BooleanField(default=True, help_text="Notify when child boards bus"),
                ),
                (
                    "deboarding",
                    models.BooleanField(default=True, help_text="Notify when child drops off"),
                ),
                (
                    "eta",
                    models.BooleanField(default=True, help_text="Notify about bus ETA"),
                ),
                (
                    "pickup_reminder",
                    models.BooleanField(default=True, help_text="Remind before pickup"),
                ),
                (
                    "drop_reminder",
                    models.BooleanField(default=True, help_text="Remind before drop-off"),
                ),
                (
                    "announcements",
                    models.BooleanField(default=True, help_text="School announcements"),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="students.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notifications_preference",
            },
        ),
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to="students.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM Token",
                "verbose_name_plural": "FCM Tokens",
                "db_table": "notifications_fcm_token",
                "indexes": [
                    models.Index(
                        fields=["parent", "is_active"],
                        name="notificatio_parent__048cab_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.CharField(
                        default=notifications.models.generate_ulid,
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("boarding", "Boarding"),
                            ("deboarding", "Deboarding"),
                            ("eta", "ETA"),
                            ("pickup_reminder", "Pickup Reminder"),
                            ("drop_reminder", "Drop Reminder"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="students.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent", "status"],
                        name="notificatio_parent__409c6f_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="notificatio_status_9a4505_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                ],
            },
        ),
    ]
