"""
Django settings for bus_kiosk_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more inform        "json": {
            "format": (
                '{"timestamp": "%(asctime)s", "level": "%(levelname)s", '
                '"logger": "%(name)s", "message": "%(message)s", '
                '"module": "%(module)s", "function": "%(funcName)s", '
                '"line": %(lineno)d}'
            ),
            "class": "pythonjsonlogger.jsonlogger.JsonFormatter",
        },n on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / "logs"
# Try to create the directory (including parents) and make a best-effort to
# ensure the running process can write into it. In some container setups the
# directory may be owned by a different user; we attempt a permissive chmod as
# a last resort to reduce permission errors when logging handlers open files.
try:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
except Exception:
    # If this fails, we continue — dictConfig will raise later if unwritable.
    pass

# Quick test: try to create and remove a temporary placeholder file. If that
# fails, attempt to relax permissions on the directory (best-effort, may be
# blocked by the container permissions). These are defensive measures to avoid
# PermissionError when logging.FileHandler opens files like '/app/logs/api.log'.
try:
    _test_file = LOGS_DIR / ".write_test"
    _test_file.open("a").close()
    _test_file.unlink()
except Exception:
    try:
        # Try to make the directory writable by everyone (best-effort).
        os.chmod(LOGS_DIR, 0o777)
    except Exception:
        # Ignore failures — we'll still try to start and let the logging
        # configuration either succeed or raise a clear error.
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproje        logging.getLogger(__name__).warning("Failed to relax logs dir permissions: %s", e)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, this MUST be set via environment variable
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-nt^m$n3edy=!)w9=b0$@)jc3r4$csehg)6a#-q2u1*n01f$zl@",  # Dev fallback only
)

# Encryption key for PII data (generate a new one for production)
# In production, this MUST be set via environment variable
ENCRYPTION_KEY = os.getenv(
    "ENCRYPTION_KEY",
    "your-32-byte-encryption-key-here-change-in-production",  # Dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety - must explicitly enable for development
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Allowed hosts configuration
# Production domains (hardcoded as they rarely change)
ALLOWED_HOSTS: list[str] = [
    "easypool.in",
    "www.easypool.in",
    "localhost",  # For health checks and internal Docker networking
    "127.0.0.1",
]

# Add environment variable hosts if specified (for flexibility)
if os.getenv("ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend([host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",")])
elif os.getenv("GITHUB_ACTIONS") == "true":
    # GitHub Actions CI environment
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1", "testserver"])
elif DEBUG:
    # Development fallback
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # For token rotation security
    "drf_spectacular",  # OpenAPI schema generation
    "drf_spectacular_sidecar",  # Self-hosted Swagger UI assets
    "corsheaders",  # CORS handling
    "django_prometheus",  # Metrics collection
    "drf_api_logger",  # API request logging
    "django_filters",  # Advanced filtering
    "django_celery_beat",  # Periodic tasks
    "django_celery_results",  # Task results storage
    "django_redis",  # Redis cache backend
    # Local apps
    "users",
    "students",
    "buses",
    "events",
    "kiosks",
    "tests",  # Test app for comprehensive testing
]

# Custom user model
AUTH_USER_MODEL = "users.User"

# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "kiosks.authentication.KioskJWTAuthentication",  # Custom kiosk authentication
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "bus_kiosk_backend.permissions.DenyByDefault",  # AWS-style: Deny unless explicitly allowed
    ],
    "DEFAULT_PAGINATION_CLASS": ("rest_framework.pagination.PageNumberPagination"),
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "login": "5/minute",
        "register": "3/minute",
        "upload": "10/minute",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # Re-enable for docs
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # API is already versioned in URLs (/api/v1/), no need for additional versioning
    # "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    # "ALLOWED_VERSIONS": ["v1"],
    # "VERSION_PARAM": "version",
    "EXCEPTION_HANDLER": "bus_kiosk_backend.exceptions.custom_exception_handler",
}

# JWT settings for Secure Kiosk Authentication
SIMPLE_JWT = {
    # Access Token (Short-lived for security - if stolen, only works 15 min)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # Refresh Token (60 days for 2-month holidays - kiosk autonomy)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=60),
    # Token Rotation (Security - old tokens become garbage every 14 min)
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Algorithm and signing
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    # Token claims
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "user_id",  # Custom User model uses user_id instead of id
    "USER_ID_CLAIM": "user_id",  # Include user_id in JWT payload
    # Blacklist checks (detects token reuse attacks)
    "BLACKLIST_TOKEN_CHECKS": ["refresh"],
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_CONCURRENCY = 4

# Celery Beat Settings
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "json": {
            "format": (
                '{"timestamp": "%(asctime)s", "level": "%(levelname)s", '
                '"logger": "%(name)s", "message": "%(message)s", '
                '"module": "%(module)s", "function": "%(funcName)s", '
                '"line": %(lineno)d}'
            ),
            "class": "pythonjsonlogger.jsonlogger.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(BASE_DIR / "logs" / "django.log"),
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 5,
            "formatter": "json",
        },
        "api_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(BASE_DIR / "logs" / "api.log"),
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 5,
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "bus_kiosk_backend": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "drf_api_logger": {
            "handlers": ["api_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "https://easypool.in",
    "https://www.easypool.in",
    "http://easypool.in",
    "http://www.easypool.in",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins for HTTPS
CSRF_TRUSTED_ORIGINS = [
    "https://easypool.in",
    "https://www.easypool.in",
]

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Bus Kiosk Backend API",
    "DESCRIPTION": "Industrial REST API for Bus Kiosk face recognition system",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "PREPROCESSING_HOOKS": [
        "bus_kiosk_backend.schema_hooks.exclude_health_endpoints",
    ],
    # Postprocessing hooks are applied after schema generation. We ensure the
    # kiosk activation endpoint is public via a postprocessing hook.
    "POSTPROCESSING_HOOKS": [
        "bus_kiosk_backend.schema_hooks.mark_activation_public",
    ],
    "SERVERS": [
        {"url": "http://localhost:8000", "description": "Development server"},
    ],
    "SECURITY": [{"Bearer": []}],
    "SECURITY_SCHEMES": {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": ("JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer {token}'"),
        }
    },
    # Self-hosted Swagger UI (no CDN)
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# OpenAPI Validation Settings
OPENAPI_VALIDATE_REQUESTS = True  # Enable request validation
OPENAPI_VALIDATE_RESPONSES = False  # Disable response validation for now
OPENAPI_FAIL_ON_ERROR = False  # Log warnings instead of failing requests

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # OpenAPI validation middleware (must be early in the pipeline)
    "bus_kiosk_backend.middleware.openapi_validation.OpenAPIValidationMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bus_kiosk_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bus_kiosk_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL if DB_ENGINE is set to PostgreSQL (Docker environment)
if os.getenv("DB_ENGINE") == "django.db.backends.postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "bus_kiosk"),
            "USER": os.getenv("DB_USER", "bus_kiosk_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "OPTIONS": {
                "connect_timeout": 10,
                "options": "-c timezone=UTC",
            },
            "CONN_MAX_AGE": 60,  # Connection pooling
            "CONN_HEALTH_CHECKS": True,
        }
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cache configuration
redis_url = os.getenv("REDIS_URL")
if redis_url and not os.getenv("GITHUB_ACTIONS"):  # Disable Redis in CI for now
    try:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": redis_url,
                "KEY_PREFIX": "bus_kiosk",
                "TIMEOUT": 300,  # 5 minutes default
            },
            "api_cache": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": redis_url,
                "KEY_PREFIX": "api",
                "TIMEOUT": 3600,  # 1 hour for API responses
            },
        }
    except Exception:
        # Fallback to memory cache if Redis fails
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "unique-snowflake",
                "KEY_PREFIX": "bus_kiosk",
                "TIMEOUT": 300,
            },
            "api_cache": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "api-cache",
                "KEY_PREFIX": "api",
                "TIMEOUT": 3600,
            },
        }
else:
    # Fallback to local memory cache for development and CI
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
            "KEY_PREFIX": "bus_kiosk",
            "TIMEOUT": 300,  # 5 minutes default
        },
        "api_cache": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "api-cache",
            "KEY_PREFIX": "api",
            "TIMEOUT": 3600,  # 1 hour for API responses
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": ("django.contrib.auth.password_validation.UserAttributeSimilarityValidator"),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
