"""
Django settings for bus_kiosk_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from typing import Any

# Load environment variables from .env file
try:
    from dotenv import load_dotenv

    # Look for .env in backend_easy directory (parent of app)
    env_path = Path(__file__).resolve().parent.parent.parent / ".env"
    if env_path.exists():
        load_dotenv(env_path)
except ImportError:
    # dotenv not installed - will use system environment variables
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Logging configuration - Environment-based (12-factor app pattern)
# CI/Docker: Set USE_FILE_LOGGING=false for console-only logging
# Production: Leave default (true) for file logging
USE_FILE_LOGGING = os.getenv("USE_FILE_LOGGING", "false").lower() == "true"

# Create logs directory only if file logging is enabled
if USE_FILE_LOGGING:
    LOGS_DIR = BASE_DIR / "logs"
    try:
        LOGS_DIR.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, this MUST be set via environment variable
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-nt^m$n3edy=!)w9=b0$@)jc3r4$csehg)6a#-q2u1*n01f$zl@",  # Dev fallback only
)

# Encryption key for PII data (generate a new one for production)
# In production, this MUST be set via environment variable
ENCRYPTION_KEY = os.getenv(
    "ENCRYPTION_KEY",
    "your-32-byte-encryption-key-here-change-in-production",  # Dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety - DEBUG is DISABLED in production
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Allowed hosts configuration - PRODUCTION ONLY
# Remove localhost entries for production security
ALLOWED_HOSTS: list[str] = [
    "easypool.in",
    "www.easypool.in",
    "api.easypool.in",  # ✅ Added: API subdomain for backend access
]

# Add environment variable hosts if specified (for flexibility)
if os.getenv("ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend([host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",")])
elif os.getenv("GITHUB_ACTIONS") == "true":
    # GitHub Actions CI environment
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1", "testserver"])
elif DEBUG:
    # Development ONLY - NEVER in production
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "channels",  # Django Channels for WebSocket support
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # For token rotation security
    "drf_spectacular",  # OpenAPI schema generation
    "drf_spectacular_sidecar",  # Self-hosted Swagger UI assets
    "corsheaders",  # CORS handling
    "django_prometheus",  # Metrics collection
    "drf_api_logger",  # API request logging
    "django_filters",  # Advanced filtering
    "django_celery_beat",  # Periodic tasks
    "django_celery_results",  # Task results storage
    "django_redis",  # Redis cache backend
    # Local apps
    "users",
    "students",
    "buses",
    "events",
    "kiosks",
    # "tests",  # REMOVED: Test app should not be in production
    # "school_dashboard",  # ARCHIVED: Replaced by Flutter frontend
    "realtime",  # Real-time WebSocket communication
]

# Custom user model
AUTH_USER_MODEL = "users.User"

# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "kiosks.authentication.KioskJWTAuthentication",  # Custom kiosk authentication
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "bus_kiosk_backend.permissions.DenyByDefault",  # AWS-style: Deny unless explicitly allowed
    ],
    "DEFAULT_PAGINATION_CLASS": ("rest_framework.pagination.PageNumberPagination"),
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "login": "5/minute",
        "register": "3/minute",
        "upload": "10/minute",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # REMOVED: BrowsableAPIRenderer should not be in production
        # "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # API is already versioned in URLs (/api/v1/), no need for additional versioning
    # "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    # "ALLOWED_VERSIONS": ["v1"],
    # "VERSION_PARAM": "version",
    "EXCEPTION_HANDLER": "bus_kiosk_backend.exceptions.custom_exception_handler",
}

# JWT settings for Secure Kiosk Authentication
SIMPLE_JWT = {
    # CRITICAL: Token lifetimes are set EXPLICITLY per token type (no global defaults used)
    # - Kiosk tokens: kiosks/token_config.py (60 days - autonomous IoT)
    # - User tokens: users/token_config.py (1 day - maximum security)
    #
    # Access Token (Short-lived for security - if stolen, only works 15 min)
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # Refresh Token - FALLBACK ONLY (should never be used, explicit config required)
    # Set to 1 day as safe default - if this is used, it means explicit config is missing
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Token Rotation (Security - old tokens become garbage every 14 min)
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Algorithm and signing
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    # Token claims
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "user_id",  # Custom User model uses user_id instead of id
    "USER_ID_CLAIM": "user_id",  # Include user_id in JWT payload
    # Blacklist checks (detects token reuse attacks)
    "BLACKLIST_TOKEN_CHECKS": ["refresh"],
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
# Store results in Django database for visibility in admin panel
CELERY_RESULT_BACKEND = "django-db"  # Uses django_celery_results app
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_CONCURRENCY = 4

# Celery Results - Keep for debugging and monitoring
CELERY_RESULT_EXPIRES = 86400  # Keep results for 24 hours (86400 seconds)

# Celery Task Routing - Route ML tasks to dedicated ML queue
CELERY_TASK_ROUTES = {
    "students.tasks.process_student_photo_embedding_task": {"queue": "ml_tasks"},
    # Other tasks go to default queue
}

# Celery Beat Settings
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Django Channels Configuration (WebSocket Support)
ASGI_APPLICATION = "bus_kiosk_backend.asgi.application"

# Channel Layers - Redis backend for WebSocket communication
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")],
            "capacity": 1500,  # Max messages per channel
            "expiry": 10,  # Message expiry in seconds
        },
    },
}

# Logging Configuration - Environment-based
# Build handlers list based on USE_FILE_LOGGING environment variable
_log_handlers: dict[str, dict[str, Any]] = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    },
}

# Add file handlers only if file logging is enabled
if USE_FILE_LOGGING:
    _log_handlers["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(LOGS_DIR / "django.log"),
        "maxBytes": 1024 * 1024 * 10,  # 10MB
        "backupCount": 5,
        "formatter": "json",
    }
    _log_handlers["api_file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(LOGS_DIR / "api.log"),
        "maxBytes": 1024 * 1024 * 10,  # 10MB
        "backupCount": 5,
        "formatter": "json",
    }

# Determine handler names for loggers
_default_handlers = ["console", "file"] if USE_FILE_LOGGING else ["console"]
_api_handlers = ["api_file"] if USE_FILE_LOGGING else ["console"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "json": {
            "format": (
                '{"timestamp": "%(asctime)s", "level": "%(levelname)s", '
                '"logger": "%(name)s", "message": "%(message)s", '
                '"module": "%(module)s", "function": "%(funcName)s", '
                '"line": %(lineno)d}'
            ),
            "class": "pythonjsonlogger.jsonlogger.JsonFormatter",
        },
    },
    "handlers": _log_handlers,
    "root": {
        "handlers": _default_handlers,
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": _default_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": _default_handlers,
            "level": "WARNING",
            "propagate": False,
        },
        "bus_kiosk_backend": {
            "handlers": _default_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "drf_api_logger": {
            "handlers": _api_handlers,
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# CORS Settings - PRODUCTION ONLY (HTTPS only)
CORS_ALLOWED_ORIGINS = [
    "https://easypool.in",
    "https://www.easypool.in",
    "https://api.easypool.in",  # ✅ Added: API subdomain for backend calls
    # REMOVED: Firebase default domain - using custom domain instead
    # "https://easypool-30af3.web.app",
    # REMOVED: HTTP localhost URLs should not be in production
    # "http://easypool.in",
    # "http://www.easypool.in",
    # "http://localhost:3000",
    # "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins for HTTPS
CSRF_TRUSTED_ORIGINS = [
    "https://easypool.in",
    "https://www.easypool.in",
    "https://api.easypool.in",  # ✅ Added: API subdomain for admin access
    # REMOVED: Firebase default domain - using custom domain instead
    # "https://easypool-30af3.web.app",
]

# Add environment variable origins if specified (for flexibility)
if os.getenv("CSRF_TRUSTED_ORIGINS"):
    csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in csrf_origins])

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Bus Kiosk Backend API",
    "DESCRIPTION": "Industrial REST API for Bus Kiosk face recognition system",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "PREPROCESSING_HOOKS": [
        "bus_kiosk_backend.schema_hooks.exclude_health_endpoints",
    ],
    # Postprocessing hooks are applied after schema generation. We ensure the
    # kiosk activation endpoint is public via a postprocessing hook.
    "POSTPROCESSING_HOOKS": [
        "bus_kiosk_backend.schema_hooks.mark_activation_public",
    ],
    "SERVERS": [
        # REMOVED: localhost should not be in production API docs
        # {"url": "http://localhost:8000", "description": "Development server"},
        {"url": "https://api.easypool.in", "description": "Production API"},
    ],
    "SECURITY": [{"Bearer": []}],
    "SECURITY_SCHEMES": {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": ("JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer {token}'"),
        }
    },
    # Self-hosted Swagger UI (no CDN)
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# OpenAPI Validation Settings - ENABLED for production security
OPENAPI_VALIDATE_REQUESTS = True  # Enable request validation
OPENAPI_VALIDATE_RESPONSES = True  # ENABLED: Response validation for production
OPENAPI_FAIL_ON_ERROR = False  # Log warnings instead of failing requests

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise for static files
    # CORS must be before CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",
    # Security headers middleware (CSP, OWASP headers)
    "bus_kiosk_backend.middleware.SecurityHeadersMiddleware",
    # OpenAPI validation middleware (must be early in the pipeline)
    "bus_kiosk_backend.middleware.openapi_validation.OpenAPIValidationMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bus_kiosk_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Custom templates directory
        "APP_DIRS": True,  # Django admin needs this for its own templates
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bus_kiosk_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL if DB_ENGINE is set to PostgreSQL (Docker environment)
if os.getenv("DB_ENGINE") == "django.db.backends.postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "bus_kiosk"),
            "USER": os.getenv("DB_USER", "bus_kiosk_user"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "OPTIONS": {
                "connect_timeout": 10,
                "options": "-c timezone=UTC",
            },
            "CONN_MAX_AGE": 60,  # Connection pooling
            "CONN_HEALTH_CHECKS": True,
        }
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cache configuration
redis_url = os.getenv("REDIS_URL")
if redis_url and not os.getenv("GITHUB_ACTIONS"):  # Disable Redis in CI for now
    try:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": redis_url,
                "KEY_PREFIX": "bus_kiosk",
                "TIMEOUT": 300,  # 5 minutes default
            },
            "api_cache": {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": redis_url,
                "KEY_PREFIX": "api",
                "TIMEOUT": 3600,  # 1 hour for API responses
            },
        }
    except Exception:
        # Fallback to memory cache if Redis fails
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "unique-snowflake",
                "KEY_PREFIX": "bus_kiosk",
                "TIMEOUT": 300,
            },
            "api_cache": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "api-cache",
                "KEY_PREFIX": "api",
                "TIMEOUT": 3600,
            },
        }
else:
    # Fallback to local memory cache for development and CI
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
            "KEY_PREFIX": "bus_kiosk",
            "TIMEOUT": 300,  # 5 minutes default
        },
        "api_cache": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "api-cache",
            "KEY_PREFIX": "api",
            "TIMEOUT": 3600,  # 1 hour for API responses
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": ("django.contrib.auth.password_validation.UserAttributeSimilarityValidator"),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# API-only backend - only Django admin static files are served (automatically by Django)
# No custom static files needed (frontend is Flutter)

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # Django admin will collect its static files here

# Media files (User uploads - student photos, etc.)
# These ARE served via API endpoints for Flutter to display
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Google Maps API Key
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY", "")
