# Generated by Django 5.2.7 on 2025-10-28 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kiosk",
            fields=[
                (
                    "kiosk_id",
                    models.CharField(
                        help_text="Unique kiosk device identifier (e.g., KIOSK001, BUS123-KIOSK)",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True,
                        help_text="Current firmware version installed on device",
                        max_length=50,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last heartbeat received from device",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this kiosk is active and accepting requests",
                    ),
                ),
                (
                    "battery_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Battery level percentage (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "storage_used_mb",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Storage used in MB on the device",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this kiosk was registered"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this kiosk record was last updated",
                    ),
                ),
                (
                    "bus",
                    models.OneToOneField(
                        blank=True,
                        help_text="Bus this kiosk is installed on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kiosk",
                        to="buses.bus",
                    ),
                ),
            ],
            options={
                "db_table": "kiosks",
                "ordering": ["kiosk_id"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "log_id",
                    models.BigAutoField(
                        help_text="Auto-incrementing log entry ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARN", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        help_text="Log level severity",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Log message content")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data as JSON",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this log entry was created",
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Kiosk that generated this log entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="kiosks.kiosk",
                    ),
                ),
            ],
            options={
                "db_table": "device_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BusLocation",
            fields=[
                (
                    "location_id",
                    models.BigAutoField(
                        help_text="Auto-incrementing location entry ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.FloatField(help_text="GPS latitude coordinate")),
                ("longitude", models.FloatField(help_text="GPS longitude coordinate")),
                (
                    "accuracy",
                    models.FloatField(blank=True, help_text="GPS accuracy in meters", null=True),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="Speed in km/h", null=True),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Heading/bearing in degrees (0-360)",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="When this location was recorded by the kiosk"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this location was received by the server",
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Kiosk/bus that sent this location update",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="kiosks.kiosk",
                    ),
                ),
            ],
            options={
                "db_table": "bus_locations",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="KioskActivationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="HMAC-SHA256 hash of activation token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this activation token was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Token expires after 24 hours"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this token has been used for activation",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was used for activation",
                        null=True,
                    ),
                ),
                (
                    "used_by_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that used this token",
                        null=True,
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Kiosk this activation token belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_tokens",
                        to="kiosks.kiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Activation Token",
                "verbose_name_plural": "Kiosk Activation Tokens",
                "db_table": "kiosk_activation_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KioskStatus",
            fields=[
                (
                    "kiosk",
                    models.OneToOneField(
                        help_text="Kiosk this status belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="status",
                        serialize=False,
                        to="kiosks.kiosk",
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(help_text="Last heartbeat received from kiosk"),
                ),
                (
                    "database_version",
                    models.CharField(help_text="Timestamp of current database version", max_length=50),
                ),
                (
                    "database_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of kiosk database content (for integrity)",
                        max_length=64,
                    ),
                ),
                (
                    "student_count",
                    models.IntegerField(default=0, help_text="Number of students in kiosk database"),
                ),
                (
                    "embedding_count",
                    models.IntegerField(default=0, help_text="Number of embeddings in kiosk database"),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Battery level percentage (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_charging",
                    models.BooleanField(default=False, help_text="Is device charging"),
                ),
                (
                    "storage_available_mb",
                    models.IntegerField(blank=True, help_text="Available storage in MB", null=True),
                ),
                (
                    "camera_active",
                    models.BooleanField(default=False, help_text="Is camera currently active"),
                ),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        help_text="Network type (wifi, 4g, none)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        help_text="Kiosk app version",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_face_detected",
                    models.DateTimeField(blank=True, help_text="Last time a face was detected", null=True),
                ),
                (
                    "faces_detected_today",
                    models.IntegerField(default=0, help_text="Faces detected today"),
                ),
                (
                    "students_identified_today",
                    models.IntegerField(default=0, help_text="Students identified today"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="ok",
                        help_text="Overall kiosk status",
                        max_length=20,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last error message if any", null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this status was last updated"),
                ),
            ],
            options={
                "verbose_name": "Kiosk Status",
                "verbose_name_plural": "Kiosk Statuses",
                "db_table": "kiosk_status",
                "indexes": [
                    models.Index(fields=["status"], name="idx_kiosk_status_status"),
                    models.Index(fields=["last_heartbeat"], name="idx_kiosk_status_heartbeat"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="kiosk",
            index=models.Index(fields=["bus"], name="idx_kiosk_bus"),
        ),
        migrations.AddIndex(
            model_name="kiosk",
            index=models.Index(fields=["last_heartbeat"], name="idx_kiosk_heartbeat"),
        ),
        migrations.AddIndex(
            model_name="kiosk",
            index=models.Index(fields=["is_active"], name="idx_kiosk_active"),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(fields=["kiosk", "timestamp"], name="idx_logs_kiosk_time"),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(fields=["log_level"], name="idx_logs_level"),
        ),
        migrations.AddIndex(
            model_name="devicelog",
            index=models.Index(fields=["timestamp"], name="idx_logs_timestamp"),
        ),
        migrations.AddIndex(
            model_name="buslocation",
            index=models.Index(fields=["kiosk", "-timestamp"], name="idx_busloc_kiosk_time"),
        ),
        migrations.AddIndex(
            model_name="buslocation",
            index=models.Index(fields=["-timestamp"], name="idx_busloc_timestamp"),
        ),
        migrations.AddIndex(
            model_name="kioskactivationtoken",
            index=models.Index(fields=["token_hash"], name="idx_activation_token_hash"),
        ),
        migrations.AddIndex(
            model_name="kioskactivationtoken",
            index=models.Index(fields=["kiosk", "is_used"], name="idx_activation_kiosk_used"),
        ),
        migrations.AddIndex(
            model_name="kioskactivationtoken",
            index=models.Index(fields=["expires_at"], name="idx_activation_expires"),
        ),
    ]
