# Generated by Django 5.2.6 on 2025-10-03 20:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('kiosk_id', models.CharField(help_text='Unique kiosk device identifier (e.g., KIOSK001, BUS123-KIOSK)', max_length=100, primary_key=True, serialize=False)),
                ('api_key_hash', models.CharField(help_text='Hashed API key for device authentication', max_length=255, unique=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Current firmware version installed on device', max_length=50)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Timestamp of last heartbeat received from device', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this kiosk is active and accepting requests')),
                ('battery_level', models.PositiveIntegerField(blank=True, help_text='Battery level percentage (0-100)', null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('storage_used_mb', models.PositiveIntegerField(blank=True, help_text='Storage used in MB on the device', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this kiosk was registered')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this kiosk record was last updated')),
                ('bus', models.OneToOneField(blank=True, help_text='Bus this kiosk is installed on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk', to='buses.bus')),
            ],
            options={
                'db_table': 'kiosks',
                'ordering': ['kiosk_id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('log_id', models.BigAutoField(help_text='Auto-incrementing log entry ID', primary_key=True, serialize=False)),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], help_text='Log level severity', max_length=20)),
                ('message', models.TextField(help_text='Log message content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data as JSON')),
                ('timestamp', models.DateTimeField(default=django.db.models.functions.datetime.Now, help_text='When this log entry was created')),
                ('kiosk', models.ForeignKey(help_text='Kiosk that generated this log entry', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kiosks.kiosk')),
            ],
            options={
                'db_table': 'device_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='kiosk',
            index=models.Index(fields=['bus'], name='idx_kiosk_bus'),
        ),
        migrations.AddIndex(
            model_name='kiosk',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['last_heartbeat'], name='idx_kiosk_heartbeat'),
        ),
        migrations.AddIndex(
            model_name='kiosk',
            index=models.Index(fields=['is_active'], name='idx_kiosk_active'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['kiosk', 'timestamp'], name='idx_logs_kiosk_time'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['log_level'], name='idx_logs_level'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['timestamp'], name='idx_logs_timestamp'),
        ),
    ]
