# Generated by Django 5.2.6 on 2025-10-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0001_initial"),
        ("kiosks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="kiosk",
            name="idx_kiosk_heartbeat",
        ),
        migrations.AddIndex(
            model_name="kiosk",
            index=models.Index(fields=["last_heartbeat"], name="idx_kiosk_heartbeat"),
        ),
    ]
