# Generated by Django 5.2.7 on 2025-10-30 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KioskActivationToken",
        ),
    ]
