# Generated by Django 5.2.6 on 2025-10-03 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0002_remove_kiosk_idx_kiosk_heartbeat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kiosk",
            name="battery_level",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Battery level percentage (0-100)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
