# Generated by Django 5.2.7 on 2025-11-06 13:25

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove AppRelease model that was temporarily added.
    This migration safely drops the table if it exists in production.
    """

    dependencies = [
        ("kiosks", "0002_kiosk_firebase_uid"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS kiosks_apprelease;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
