# Generated by Django 5.2.7 on 2025-11-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0003_remove_app_release"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOSAlert",
            fields=[
                (
                    "alert_id",
                    models.BigAutoField(
                        help_text="Auto-incrementing alert ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, help_text="GPS latitude at time of alert", null=True),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="GPS longitude at time of alert",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("false_alarm", "False Alarm"),
                        ],
                        default="active",
                        help_text="Current status of the alert",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message/notes from the kiosk operator",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (battery level, network status, etc.)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the alert was created"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the alert was first acknowledged by staff",
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, help_text="When the alert was resolved", null=True),
                ),
                (
                    "acknowledged_by",
                    models.CharField(
                        blank=True,
                        help_text="Name/ID of person who acknowledged the alert",
                        max_length=255,
                    ),
                ),
                (
                    "resolved_by",
                    models.CharField(
                        blank=True,
                        help_text="Name/ID of person who resolved the alert",
                        max_length=255,
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Kiosk that triggered the SOS alert",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_alerts",
                        to="kiosks.kiosk",
                    ),
                ),
            ],
            options={
                "db_table": "sos_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["kiosk", "-created_at"], name="idx_sos_kiosk_time"),
                    models.Index(fields=["status"], name="idx_sos_status"),
                    models.Index(fields=["-created_at"], name="idx_sos_created"),
                ],
            },
        ),
    ]
