# Generated by Django 5.2.6 on 2025-10-06 01:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0003_change_battery_level_to_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicelog",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this log entry was created",
            ),
        ),
        migrations.CreateModel(
            name="KioskStatus",
            fields=[
                (
                    "kiosk",
                    models.OneToOneField(
                        help_text="Kiosk this status belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="status",
                        serialize=False,
                        to="kiosks.kiosk",
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        help_text="Last heartbeat received from kiosk"
                    ),
                ),
                (
                    "database_version",
                    models.CharField(
                        help_text="Timestamp of current database version", max_length=50
                    ),
                ),
                (
                    "database_hash",
                    models.CharField(
                        blank=True,
                        help_text="Content hash of kiosk database (for integrity)",
                        max_length=32,
                    ),
                ),
                (
                    "student_count",
                    models.IntegerField(
                        default=0, help_text="Number of students in kiosk database"
                    ),
                ),
                (
                    "embedding_count",
                    models.IntegerField(
                        default=0, help_text="Number of embeddings in kiosk database"
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Battery level percentage (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_charging",
                    models.BooleanField(default=False, help_text="Is device charging"),
                ),
                (
                    "storage_available_mb",
                    models.IntegerField(
                        blank=True, help_text="Available storage in MB", null=True
                    ),
                ),
                (
                    "camera_active",
                    models.BooleanField(
                        default=False, help_text="Is camera currently active"
                    ),
                ),
                (
                    "network_type",
                    models.CharField(
                        blank=True,
                        help_text="Network type (wifi, 4g, none)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        help_text="Kiosk app version",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_face_detected",
                    models.DateTimeField(
                        blank=True, help_text="Last time a face was detected", null=True
                    ),
                ),
                (
                    "faces_detected_today",
                    models.IntegerField(default=0, help_text="Faces detected today"),
                ),
                (
                    "students_identified_today",
                    models.IntegerField(
                        default=0, help_text="Students identified today"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="ok",
                        help_text="Overall kiosk status",
                        max_length=20,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error message if any", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this status was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Status",
                "verbose_name_plural": "Kiosk Statuses",
                "db_table": "kiosk_status",
                "indexes": [
                    models.Index(fields=["status"], name="idx_kiosk_status_status"),
                    models.Index(
                        fields=["last_heartbeat"], name="idx_kiosk_status_heartbeat"
                    ),
                ],
            },
        ),
    ]
