# Generated by Django 5.2.6 on 2025-10-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0004_add_kiosk_sync_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskActivationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="HMAC-SHA256 hash of activation token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this activation token was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Token expires after 24 hours"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this token has been used for activation",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this token was used for activation",
                        null=True,
                    ),
                ),
                (
                    "used_by_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that used this token",
                        null=True,
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Kiosk this activation token belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_tokens",
                        to="kiosks.kiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kiosk Activation Token",
                "verbose_name_plural": "Kiosk Activation Tokens",
                "db_table": "kiosk_activation_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token_hash"], name="idx_activation_token_hash"
                    ),
                    models.Index(
                        fields=["kiosk", "is_used"], name="idx_activation_kiosk_used"
                    ),
                    models.Index(fields=["expires_at"], name="idx_activation_expires"),
                ],
            },
        ),
    ]
