# Generated by Django 5.2.7 on 2025-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0004_sosalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiosk",
            name="git_commit_sha",
            field=models.CharField(
                blank=True,
                help_text="Git commit SHA of current kiosk app build",
                max_length=40,
                null=True,
            ),
        ),
    ]
