# Generated by Django 5.2.6 on 2025-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0005_kioskactivationtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kiosk",
            name="api_key_hash",
        ),
        migrations.AlterField(
            model_name="kiosk",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this kiosk is active and accepting requests",
            ),
        ),
    ]
