# Generated by Django 5.2.7 on 2025-11-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0005_add_git_commit_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiosk",
            name="schedule",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Bus operation schedule: {'operation_hours': [{'start': '08:00', 'end': '10:00'}]}",
            ),
        ),
    ]
