# Generated by Django 5.2.6 on 2025-10-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0006_remove_api_key_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kioskstatus",
            name="database_hash",
            field=models.CharField(
                blank=True,
                help_text="Content hash of kiosk database (for integrity)",
                max_length=64,
            ),
        ),
    ]
