# Generated by Django 5.2.7 on 2025-11-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosks", "0006_kiosk_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Schedule name (e.g., 'Morning Shift', 'Full Day')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this schedule"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schedule is available for selection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Operation Timing",
                "verbose_name_plural": "Operation Timings",
                "db_table": "operation_timings",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="kiosk",
            name="schedule",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="DEPRECATED: Use operation_timing instead. Legacy field for backward compatibility.",
            ),
        ),
        migrations.CreateModel(
            name="OperationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(help_text="Start time (e.g., 08:00)")),
                ("end_time", models.TimeField(help_text="End time (e.g., 10:00)")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (0 = first slot)"
                    ),
                ),
                (
                    "timing",
                    models.ForeignKey(
                        help_text="Operation timing this slot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="kiosks.operationtiming",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation Slot",
                "verbose_name_plural": "Operation Slots",
                "db_table": "operation_slots",
                "ordering": ["timing", "order", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="kiosk",
            name="operation_timing",
            field=models.ForeignKey(
                blank=True,
                help_text="Operation schedule for this kiosk (select from predefined timings)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kiosks",
                to="kiosks.operationtiming",
            ),
        ),
    ]
