# Generated by Django 5.2.7 on 2025-10-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0007_alter_kioskstatus_database_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusLocation",
            fields=[
                (
                    "location_id",
                    models.BigAutoField(
                        help_text="Auto-incrementing location entry ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.FloatField(help_text="GPS latitude coordinate")),
                ("longitude", models.FloatField(help_text="GPS longitude coordinate")),
                (
                    "accuracy",
                    models.FloatField(blank=True, help_text="GPS accuracy in meters", null=True),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="Speed in km/h", null=True),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Heading/bearing in degrees (0-360)",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="When this location was recorded by the kiosk"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this location was received by the server",
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        help_text="Kiosk/bus that sent this location update",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="kiosks.kiosk",
                    ),
                ),
            ],
            options={
                "db_table": "bus_locations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["kiosk", "-timestamp"], name="idx_busloc_kiosk_time"),
                    models.Index(fields=["-timestamp"], name="idx_busloc_timestamp"),
                ],
            },
        ),
    ]
