# Generated by Django 5.2.7 on 2025-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kiosks", "0007_operationtiming_alter_kiosk_schedule_operationslot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskstatus",
            name="device_temperature",
            field=models.IntegerField(
                blank=True,
                help_text="Device battery temperature in deciselsius (Celsius * 10, e.g., 350 = 35.0°C)",
                null=True,
            ),
        ),
    ]
