# Generated by Django 5.2.7 on 2025-10-30 04:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Date of attendance record")),
                (
                    "morning_boarded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student boarded in the morning",
                    ),
                ),
                (
                    "morning_time",
                    models.DateTimeField(
                        blank=True, help_text="Time of morning boarding", null=True
                    ),
                ),
                (
                    "afternoon_boarded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student boarded in the afternoon",
                    ),
                ),
                (
                    "afternoon_time",
                    models.DateTimeField(
                        blank=True, help_text="Time of afternoon boarding", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("partial", "Partial"),
                        ],
                        help_text="Overall attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student attendance record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["student", "date"], name="idx_attendance_student_date"
                    ),
                    models.Index(fields=["date"], name="idx_attendance_date"),
                ],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="BoardingEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        editable=False,
                        help_text="ULID primary key for global uniqueness and time sorting",
                        max_length=26,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kiosk_id",
                    models.CharField(
                        help_text="Kiosk device identifier", max_length=100
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Face recognition confidence score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="When the boarding event occurred"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="GPS latitude coordinate", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="GPS longitude coordinate", null=True
                    ),
                ),
                (
                    "bus_route",
                    models.CharField(
                        blank=True, help_text="Bus route identifier", max_length=100
                    ),
                ),
                (
                    "face_image_url",
                    models.TextField(
                        blank=True,
                        help_text="S3 URL to face image for verification (optional)",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        help_text="Face recognition model version used", max_length=50
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata as JSON"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created in database",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who boarded the bus",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_events",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "boarding_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["student", "timestamp"], name="idx_events_student_time"
                    ),
                    models.Index(
                        fields=["kiosk_id", "timestamp"], name="idx_events_kiosk_time"
                    ),
                    models.Index(fields=["timestamp"], name="idx_events_timestamp"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence_score__gte", 0.0),
                            ("confidence_score__lte", 1.0),
                        ),
                        name="chk_confidence_score_range",
                    )
                ],
            },
        ),
    ]
