# Generated by Django 5.2.7 on 2025-11-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingevent",
            name="confirmation_face_1",
            field=models.BinaryField(
                blank=True,
                help_text="First confirmation face image (112x112 JPEG, ~5-10KB)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="boardingevent",
            name="confirmation_face_2",
            field=models.BinaryField(
                blank=True,
                help_text="Second confirmation face image (112x112 JPEG, ~5-10KB)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="boardingevent",
            name="confirmation_face_3",
            field=models.BinaryField(
                blank=True,
                help_text="Third confirmation face image (112x112 JPEG, ~5-10KB)",
                null=True,
            ),
        ),
    ]
