# Generated by Django 5.2.7 on 2025-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_add_confirmation_faces"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingevent",
            name="confirmation_face_1_gcs",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GCS path for first confirmation face (112x112 JPEG, ~5-10KB)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="boardingevent",
            name="confirmation_face_2_gcs",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GCS path for second confirmation face (112x112 JPEG, ~5-10KB)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="boardingevent",
            name="confirmation_face_3_gcs",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GCS path for third confirmation face (112x112 JPEG, ~5-10KB)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="boardingevent",
            name="confirmation_face_1",
            field=models.BinaryField(
                blank=True,
                help_text="[DEPRECATED] Use confirmation_face_1_gcs instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boardingevent",
            name="confirmation_face_2",
            field=models.BinaryField(
                blank=True,
                help_text="[DEPRECATED] Use confirmation_face_2_gcs instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boardingevent",
            name="confirmation_face_3",
            field=models.BinaryField(
                blank=True,
                help_text="[DEPRECATED] Use confirmation_face_3_gcs instead",
                null=True,
            ),
        ),
    ]
