# Generated by Django 5.2.7 on 2025-11-15 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_add_gcs_confirmation_faces"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardingevent",
            name="confirmation_face_1",
        ),
        migrations.RemoveField(
            model_name="boardingevent",
            name="confirmation_face_2",
        ),
        migrations.RemoveField(
            model_name="boardingevent",
            name="confirmation_face_3",
        ),
    ]
