# Generated by Django 5.2.7 on 2025-11-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_deprecated_binary_fields"),
        ("students", "0004_add_approval_to_parent_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardingevent",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Student who boarded the bus (null for unidentified faces)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_events",
                to="students.student",
            ),
        ),
    ]
