# Generated by Django 5.2.7 on 2025-11-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_add_backend_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingevent",
            name="backend_config_version",
            field=models.IntegerField(
                blank=True,
                help_text="ML config version used for backend verification (from BackendModelConfiguration)",
                null=True,
            ),
        ),
    ]
