# Generated by Django 5.2.7 on 2025-10-30 05:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "stop_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stop name (e.g., 'Main Gate', 'North Entrance')",
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, help_text="Latitude coordinate", max_digits=10
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude coordinate",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this stop is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this stop was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this stop was last updated"
                    ),
                ),
            ],
            options={
                "db_table": "bus_stops",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="idx_stops_active"),
                    models.Index(
                        fields=["latitude", "longitude"], name="idx_stops_coords"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "route_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Route name (e.g., 'Route A', 'North Loop')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the route"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#0072B2",
                        help_text="Hex color for map display (e.g., #FF5733)",
                        max_length=7,
                    ),
                ),
                (
                    "line_pattern",
                    models.CharField(
                        choices=[("solid", "Solid Line"), ("dashed", "Dashed Line")],
                        default="solid",
                        help_text="Line pattern for map visualization",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this route is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this route was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this route was last updated"
                    ),
                ),
            ],
            options={
                "db_table": "routes",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="idx_routes_active")
                ],
            },
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "bus_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bus_number",
                    models.CharField(
                        help_text="School-assigned bus number (e.g., 'BUS-001', 'B-12')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        help_text="Vehicle license plate number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of passengers",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Kiosk device identifier installed on this bus",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        help_text="Current operational status",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Bus manufacturer", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, help_text="Bus model", max_length=100),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Manufacturing year", null=True
                    ),
                ),
                (
                    "last_maintenance",
                    models.DateField(
                        blank=True, help_text="Date of last maintenance", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this bus was added to the system",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this bus record was last updated"
                    ),
                ),
                (
                    "last_student_update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time students/embeddings changed for this bus",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Route this bus is assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buses",
                        to="buses.route",
                    ),
                ),
            ],
            options={
                "db_table": "buses",
                "ordering": ["bus_number"],
                "indexes": [
                    models.Index(
                        fields=["route", "status"], name="idx_buses_route_status"
                    ),
                    models.Index(fields=["device_id"], name="idx_buses_device"),
                    models.Index(fields=["license_plate"], name="idx_buses_license"),
                    models.Index(fields=["bus_number"], name="idx_buses_number"),
                    models.Index(fields=["status"], name="idx_buses_status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Order of this stop in the route (1-based)"
                    ),
                ),
                (
                    "waypoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Path coordinates to NEXT stop: [{lat, lon}, ...]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus_stop",
                    models.ForeignKey(
                        help_text="Bus stop on this route",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="buses.busstop",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route this stop belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="buses.route",
                    ),
                ),
            ],
            options={
                "db_table": "route_stops",
                "ordering": ["route", "sequence"],
                "indexes": [
                    models.Index(fields=["route", "sequence"], name="idx_routestop")
                ],
                "unique_together": {("route", "bus_stop"), ("route", "sequence")},
            },
        ),
    ]
