# Generated by Django 5.2.6 on 2025-10-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="last_student_update",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last time students/embeddings changed for this bus",
            ),
        ),
    ]
