# Generated by Django 5.2.7 on 2025-11-03 11:40

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="encoded_polyline",
            field=models.TextField(
                blank=True,
                help_text="Google-encoded polyline for the entire route path",
            ),
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "waypoint_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=7, help_text="Latitude coordinate", max_digits=10),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude coordinate",
                        max_digits=10,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata: {type: 'bus_stop'/'path_adjustment', name: '...', ...}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "waypoints",
                "indexes": [models.Index(fields=["latitude", "longitude"], name="idx_waypoints_coords")],
            },
        ),
        migrations.CreateModel(
            name="RouteWaypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Order of this waypoint in the route (1-based)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route this waypoint belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_waypoints",
                        to="buses.route",
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        help_text="Waypoint on this route",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="buses.waypoint",
                    ),
                ),
            ],
            options={
                "db_table": "route_waypoints",
                "ordering": ["route", "sequence"],
                "indexes": [models.Index(fields=["route", "sequence"], name="idx_route_waypoints")],
                "unique_together": {("route", "sequence"), ("route", "waypoint")},
            },
        ),
    ]
