# Generated by Django 5.2.7 on 2025-11-05 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="routewaypoint",
            unique_together={("route", "sequence")},
        ),
    ]
