# Generated by Django 5.2.7 on 2025-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0002_allow_duplicate_waypoints_in_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="conductor_address",
            field=models.TextField(blank=True, help_text="Conductor's address"),
        ),
        migrations.AddField(
            model_name="bus",
            name="conductor_name",
            field=models.CharField(blank=True, help_text="Conductor's full name", max_length=200),
        ),
        migrations.AddField(
            model_name="bus",
            name="conductor_phone",
            field=models.CharField(blank=True, help_text="Conductor's contact number", max_length=20),
        ),
        migrations.AddField(
            model_name="bus",
            name="driver_address",
            field=models.TextField(blank=True, help_text="Driver's address"),
        ),
        migrations.AddField(
            model_name="bus",
            name="driver_license_number",
            field=models.CharField(blank=True, help_text="Driver's license number", max_length=50),
        ),
        migrations.AddField(
            model_name="bus",
            name="driver_name",
            field=models.CharField(blank=True, help_text="Driver's full name", max_length=200),
        ),
        migrations.AddField(
            model_name="bus",
            name="driver_phone",
            field=models.CharField(blank=True, help_text="Driver's contact number", max_length=20),
        ),
    ]
