# Generated by Django 5.2.7 on 2025-10-22 11:59

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0002_add_kiosk_sync_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="route",
            name="stops",
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "stop_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID primary key",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stop name (e.g., 'Main Gate', 'North Entrance')",
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=7, help_text="Latitude coordinate", max_digits=10),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude coordinate",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this stop is currently active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When this stop was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When this stop was last updated"),
                ),
            ],
            options={
                "db_table": "bus_stops",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="idx_stops_active"),
                    models.Index(fields=["latitude", "longitude"], name="idx_stops_coords"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Order of this stop in the route (1-based)"),
                ),
                (
                    "waypoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Path coordinates to NEXT stop: [{lat, lon}, ...]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus_stop",
                    models.ForeignKey(
                        help_text="Bus stop on this route",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="buses.busstop",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        help_text="Route this stop belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="buses.route",
                    ),
                ),
            ],
            options={
                "db_table": "route_stops",
                "ordering": ["route", "sequence"],
                "indexes": [models.Index(fields=["route", "sequence"], name="idx_routestop")],
                "unique_together": {("route", "bus_stop"), ("route", "sequence")},
            },
        ),
    ]
