# Generated by Django 5.2.7 on 2025-11-11 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0003_add_driver_conductor_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of passengers",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
