# Generated by Django 5.2.7 on 2025-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buses", "0003_remove_route_schedule_remove_route_stops_busstop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="color_code",
            field=models.CharField(
                default="#0072B2",
                help_text="Hex color for map display (e.g., #FF5733)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="line_pattern",
            field=models.CharField(
                choices=[("solid", "Solid Line"), ("dashed", "Dashed Line")],
                default="solid",
                help_text="Line pattern for map visualization",
                max_length=20,
            ),
        ),
    ]
